### ISSUE TITLE
Amazing apk size

### ISSUE THREAD

**Issue by birkanfirat** [AmaniTechnologiesLtd/Android_SDK_V2_Public#1]
When I create a project from scratch and implement the amani sdk, the apk file is 86 Mb. This size is huge. 
You have to do something to reduce it. 

Or tell me what to do.

<img width="808" alt="image" src="https://user-images.githubusercontent.com/26115864/214312001-5c1cff6a-8f61-4f2d-ad1d-3885534197c2.png">

<img width="467" alt="image" src="https://user-images.githubusercontent.com/26115864/214312459-01322c6a-9293-473c-bd70-803b9000032f.png">

**Comment by munir-amani** [comment]
This is related to your approach to getting an application (APK).
Only 1 architecture that kind of simple application with our SDK will be nearly **25-35MB** 

Please don't forget we are providing you with a binary (compiled) framework so you can't compile it again for your supported CPU architecture.  You need to put our sources in your application and the application automatically chose which architecture is supported and uses that binary this will give you that kind of big file because there are no needed binary files still exist in your application(APK)

Creating a small application won't be your concern; it must be what is the size of the application in store 

- You generate a generic application for all architecture of the CPU this means there are different compiled sources in the APK file and those never in use. This approach is a little bit old because there are too many different architectures on the device market and the stores come with 2 new approaches; the first one you can create specific APK files for every supported CPU architecture of your application and upload them separately, second with [Android Application Bundle(AAB)](https://developer.android.com/guide/app-bundle) and  [Huawei App Bundle Distribution (AAB)](https://developer.huawei.com/consumer/en/agconnect/app-bundle/), this new packaging system still gives you a big file but when the customer tries to get it from the store; store detect architecture of CPU and gave only related binaries. 

- You get it in debug mode this will increase a bit and we do not advise publishing your app in debug mode please choose release mode
